#
# Nginxのインストールおよび設定
#
- name: Nginxをインストール
  yum:
    name: nginx

- name: Nginx自動起動
  service:
    name: nginx
    enabled: yes

- name: Nginx設定
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx