#
# MySQLのインストールおよび設定
#
- name: MySQLのリポジトリを追加
  shell: rpm -Uvh https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm

- name: MySQLをインストール
  yum:
    name: yum-utils, MySQL-python, mysql-community-server
    state: installed

- name: MySQLを起動
  service:
    name: mysqld
    state: started
    enabled: yes

- name: 必須ライブラリをインストール
  yum:
    name: MySQL-python
    state: present
    enablerepo: epel

- name: .my.cnfの配置
  template:
    src: 'templates/my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: root

- name: MySQLの初期パスワード取得
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: mysql_default_password

- name: MySQLのrootパスワード変更
  shell: mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "set password for root@'localhost'=password('{{ db_password_root }}');"

- name: DB作成
  mysql_db:
    name: ”{{ db_name }}”
    login_password: "{{ db_password_root }}"
    state: present

- name: ユーザー作成
  mysql_user:
    name: ”{{ db_user }}”
    login_password: "{{ db_password_root }}"
    password: ”{{ db_password }}”
    priv: '*.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - '%'
    - 'localhost'